name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: |
          composer install

      - name: Run tests
        run: |
          ./vendor/bin/phpunit

      - name: Deploy to Test
        if: github.ref == 'refs/heads/dev'
        run: |
          git checkout test
          git merge dev
          git push origin test

      - name: Deploy to Production
        if: github.ref == 'refs/heads/test'
        run: |
          git checkout main
          git merge test
          git push origin main
